### ISSUE TITLE
Promise.race is NOT one success, all success

### ISSUE THREAD

**Issue by CarterLi** [csvwolf/promise-foreach#5]
Promise.race IMMEDIATELY rejects or resolves after one promise rejects or resolves. 

That is: Promise.race will be REJECTED if the first promise is rejected. It's `one success, all success` only the first fulfilled promise resolves.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race

This is my implementation that offers `one success, all success`: https://segmentfault.com/a/1190000013125262

~~其实就是广告帖~~

**Comment by csvwolf** [comment]
You are right, my description is not accurate. Thanks
